# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        mappings:
            AppBundle:
                mapping:              true
                type:                 yml
                dir:                  "Resources/config/doctrine"

        resolve_target_entities:
            SaleBundle\Model\AddressInterface: AppBundle\Entity\Address
            SaleBundle\Model\ProductInterface: AppBundle\Entity\Product
            SaleBundle\Model\OrderInterface: AppBundle\Entity\Order
            SaleBundle\Model\OrderItemInterface: AppBundle\Entity\OrderItem
            SaleBundle\Model\DiscountInterface: AppBundle\Entity\Discount
            SaleBundle\Model\CustomerInterface: AppBundle\Entity\User