AppBundle\Entity\Accessory:
    type: entity
    uniqueConstraints:
        UNIQ_ACCESS_LABEL:
            columns:
                - label
    fields:
        photo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false

    manyToMany:
        configurations:
            targetEntity: AppBundle\Entity\Configuration
            cascade: ["persist", "remove"]
            fetch: LAZY
            mappedBy: "accessories"
