SaleBundle\Model\Product:
    type: mappedSuperclass
    uniqueConstraints:
        UNIQ_REFERENCE:
            columns:
                - reference
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        reference:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 8
            scale: 2
